version: "3"

services:
    core:
        container_name: halo-core
        build: ./core
        command: >
          gunicorn -b 0.0.0.0:8000
            --access-logfile -
            --reload
            --workers=3
            --threads=3
            "core.app:create_app()"
        volumes:
          - ./core:/core
        env_file:
            - '.env'
        ports:
            - "8000:8000"