version: "3.9"

services:
    database:
      container_name: halo-db
      image: 'postgres:9.5'
      env_file:
        - '.env'
      ports:
        - '5432:5432'

    ipfs:
        container_name: halo-ipfs
        build: ./ipfs
        env_file:
            - '.env'
        ports:
            - "4000:4001"
            - "8080:8080"
            - "5002:5002"

    cryptographer:
        container_name: halo-cryptographer
        build: ./cryptographer
        command: >
          gunicorn -b 0.0.0.0:8000
            --access-logfile -
            --reload
            --workers=3
            --threads=3
            "cryptographer.app:create_app()"
        volumes:
          - ./cryptographer:/cryptographer
        env_file:
            - '.env'
        ports:
            - "8000:8000"