version: "3"

networks:
  test:

services:
  orbit:
    container_name: halo-orbit
    build: ../ipfs/orbit
    command: >
      node app.js
    networks:
      - test
    env_file:
      - '.env'
    volumes:
      - ../ipfs/orbit/ipfs:/usr/src/app/ipfs
    ports:
      - "4000:4000"