version: "3.9"

networks:
  test:

services:
  core:
    container_name: halo-core
    build: ../core
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        --workers=1
        --threads=3
        "core.app:create_app()"
    depends_on:
      - orbit
    networks:
      - test
    volumes:
      - ../core:/core
    env_file:
      - '.env'
    networks:
      - test
    ports:
        - "8001:8000"

  orbit:
    container_name: halo-orbit
    build: ../ipfs
    command: node app.js
    env_file: .env    
    networks:
      - test
    volumes:
      - ../ipfs/ipfs:/home/node/ipfs
      - ../ipfs/orbitdb:/home/node/orbitdb
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
