version: "3.9"

networks:
  test:

services:
  core:
    container_name: halo-core
    build: ../core
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        --workers=3
        --threads=3
        "core.app:create_app()"
    env_file:
      - '.env'
    networks:
      - test
    volumes:
      - ../core:/core
    ports:
        - "8000:8000"