# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Org3
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ExternalMSP

        # ID to load the MSP definition as
        ID: ExternalMSP

        MSPDir: ../organizations/peerOrganizations/external.halonetwork.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ExternalMSP.admin', 'ExternalMSP.peer', 'ExternalMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ExternalMSP.admin', 'ExternalMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ExternalMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ExternalMSP.peer')"
